services:
  team-service:
    build:
      context: team_service
      target: builder
    environment: 
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - MONGO_URL=${MONGO_URL}
      - CALLBACK_URL=${CALLBACK_URL}
    networks:
      - team-service_default
    restart: always
    ports: 
      - '8000:8000'

networks:
  team-service_default:
    driver: bridge
    external: true