services:
  team-service:
    build:
      context:team_service
    target: builder
    environment: 
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - MONGO_URL=${MONGO_URL}
    restart: always
    ports: 
      - '8000:8000'
