services:
  web: 
    environment:
     - SECRET_KEY=django-insecure-l-6vx$ms8fu9(lir$p2r9!$^w0fupdiq)b8k#1tc1aq)m_o+17
     - DEBUG=1
     - MONGO_URL=mongodb+srv://ubrimania:hola1234@cluster0.m2jp5un.mongodb.net/test?retryWrites=true&w=majority
    build:
      context: team_service
      target: builder
    restart: always
    ports: 
      - '8000:8000'
